### ISSUE TITLE
Root DNS not resolving to www.rtp-aws.org

### ISSUE THREAD

**Issue by Sed3000** [rtp-aws/rtp_aws_website#13]
DNS Entry *.rtp-aws.org is not working.
No DNS entry for the root domain.

Add eitther "@"  or rtp.-aws.org to point to the same entry as www.

**Comment by netskink** [comment]
I added the @ one and now I have just the "" one.
see attached.  
<img width="1008" alt="Screen Shot 2022-01-05 at 07 29 01" src="https://user-images.githubusercontent.com/4422172/148217906-2171a71b-87cf-425d-97ed-3e8812512b5b.png">

**Comment by netskink** [comment]
@haider0324 says http://rtp-aws.org works for him.  I'm thinking the first entry in the screenshot is what fixed it for him.  Consquently, the `@.rtp-aws.org` A record should be deleted.  That was the first attempt at fixing this and is most likely incorrect.

**Comment by netskink** [comment]
I deleted the `@` entry mentioned above. If the issue goes away, and no one complains in a few days, I'll close the issue.

**Comment by netskink** [comment]
egads, its not working for me now.  I removed the first entry in the screenshot.

**Comment by netskink** [comment]
Current setup
![Screenshot from 2022-01-05 12-23-49](https://user-images.githubusercontent.com/4422172/148261596-8d4f84a4-a347-4ddf-b940-1796d72451a9.png)

**Comment by netskink** [comment]
hmm. perhaps that is the fix. once again, let it sit for a few days.

**Comment by Sed3000** [comment]
1. Remove the *.rtp-aws.org. host record.  
2. Add a host record from rtp-aws.org to the same value as www.rtp-aws.org.  

The DNS Queries do not match for rtp-aws.org and www.rtp-aws.org.  I noticed that different browsers have respond differently to the site, MS-EDGE works, but Chrome is not working for rtp-aws.org.

**Comment by netskink** [comment]
Hmm interesting.  I have been working on the eb stuff.  Do you know how to run nalookup where you specify the dns server?  Something like ' $ nslookup foo.com dns.something.com"?  I haven't done that lately but it will say what the result is from the dns servers listed in the screenshot.  I will definitely do as you suggest but I wonder what the result is.  I'm thinking they should be identical.

**Comment by netskink** [comment]
In case you didn't understand what I was saying. check this out

```
$ nslookup www.rtp-aws.org ns-517.awsdns-00.net
Server:		ns-517.awsdns-00.net
Address:	205.251.194.5#53

Name:	www.rtp-aws.org
Address: 99.84.218.3
Name:	www.rtp-aws.org
Address: 99.84.218.99
Name:	www.rtp-aws.org
Address: 99.84.218.63
Name:	www.rtp-aws.org
Address: 99.84.218.35

davis@twenty:~/progs/eb_node_tutor 
$ nslookup rtp-aws.org ns-517.awsdns-00.net
Server:		ns-517.awsdns-00.net
Address:	205.251.194.5#53

*** Can't find rtp-aws.org: No answer

davis@twenty:~/progs/eb_node_tutor 
$ nslookup foo.rtp-aws.org ns-517.awsdns-00.net
Server:		ns-517.awsdns-00.net
Address:	205.251.194.5#53

Name:	foo.rtp-aws.org
Address: 99.84.218.3
Name:	foo.rtp-aws.org
Address: 99.84.218.63
Name:	foo.rtp-aws.org
Address: 99.84.218.35
Name:	foo.rtp-aws.org
Address: 99.84.218.99
```

If we had a host, foo then it would be resolved correctly.  However, it shows that rtp-aws.org is not working.  Let me add back the blank entry like I did  before. One moment.

**Comment by netskink** [comment]
I should have done this earlier.  thanks though for helping push this problem along.

Adding the rtp-aws.org as an Alias (A record)

![Screenshot from 2022-01-05 19-46-22](https://user-images.githubusercontent.com/4422172/148310503-60814457-881c-4bd4-bfa4-71b0e8075a16.png)

Results in this
![Screenshot from 2022-01-05 19-46-49](https://user-images.githubusercontent.com/4422172/148310566-deea02e6-b9d3-436d-9c9a-e49fff89552f.png)

Now it works. This might solve the issue.

![Screenshot from 2022-01-05 19-47-34](https://user-images.githubusercontent.com/4422172/148310606-17340f65-dd36-42e6-8571-12ade85fc79a.png)

**Comment by Sed3000** [comment]
It is working from my browsers - Edge, Firefox and Chrome.  here is my DNS Queries using dig.

*** Working: Results:
[swhite@sedcentos7 ~]$ dig rtp-aws.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> rtp-aws.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29806
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rtp-aws.org.                   IN      A

;; ANSWER SECTION:
rtp-aws.org.            50      IN      A       18.67.76.111
rtp-aws.org.            50      IN      A       18.67.76.90
rtp-aws.org.            50      IN      A       18.67.76.3
rtp-aws.org.            50      IN      A       18.67.76.53

;; Query time: 1 msec
;; SERVER: 10.1.1.7#53(10.1.1.7)
;; WHEN: Wed Jan 05 16:50:42 PST 2022
;; MSG SIZE  rcvd: 104

[swhite@sedcentos7 ~]$ dig www.rtp-aws.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> www.rtp-aws.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23275
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.rtp-aws.org.               IN      A

;; ANSWER SECTION:
www.rtp-aws.org.        60      IN      A       13.32.204.14
www.rtp-aws.org.        60      IN      A       13.32.204.124
www.rtp-aws.org.        60      IN      A       13.32.204.59
www.rtp-aws.org.        60      IN      A       13.32.204.119

;; Query time: 31 msec
;; SERVER: 10.1.1.7#53(10.1.1.7)
;; WHEN: Wed Jan 05 16:50:57 PST 2022
;; MSG SIZE  rcvd: 108

[swhite@sedcentos7 ~]$ dig www.rtp-aws.org

*** Failing: Results for rtp-aws.org

[swhite@sedcentos7 ~]$ dig rtp-aws.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> rtp-aws.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38944
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rtp-aws.org.                   IN      A

;; AUTHORITY SECTION:
rtp-aws.org.            566     IN      SOA     ns-517.awsdns-00.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 15 msec
;; SERVER: 10.1.1.7#53(10.1.1.7)
;; WHEN: Wed Jan 05 15:56:05 PST 2022
;; MSG SIZE  rcvd: 124

[swhite@sedcentos7 ~]$ dig www.rtp-aws.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.7 <<>> www.rtp-aws.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55922
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.rtp-aws.org.               IN      A

;; ANSWER SECTION:
www.rtp-aws.org.        60      IN      A       13.32.204.124
www.rtp-aws.org.        60      IN      A       13.32.204.59
www.rtp-aws.org.        60      IN      A       13.32.204.119
www.rtp-aws.org.        60      IN      A       13.32.204.14

;; Query time: 36 msec
;; SERVER: 10.1.1.7#53(10.1.1.7)
;; WHEN: Wed Jan 05 15:56:21 PST 2022
;; MSG SIZE  rcvd: 108

**Comment by netskink** [comment]
Unless someone finds a problem. Lets close it.  We can reopen if it fails.
