### ISSUE TITLE
slack invite is incorrect

### ISSUE THREAD

**Issue by netskink** [rtp-aws/rtp_aws_website#18]
@raja 

says that slack invite is not correct.

https://rtp-aws.slack.com/join/shared_invite/zt-10r9e5l4l-14XJlX~m_zU8NyT7EwoL~A#/shared-invite-legacy/error

**Comment by rajag** [comment]
@rajag

**Comment by netskink** [comment]
> @rajag

Thanks

**Comment by netskink** [comment]
updated thanks for pointing this out.
